### ISSUE TITLE
Replace ClusterTask by something else

### ISSUE THREAD

**Issue by guillaumerose** [redhat-appstudio/build-definitions#20]
I am trying to use the build-definitions with https://github.com/openshift-pipelines/pipelines-service.

With some fixes in pipelines-service (https://github.com/openshift-pipelines/pipelines-service/compare/main...guillaumerose:builddef?expand=1), the PR is triggered but I hit an issue: ClusterTask doesn't exist on KCP and all definitions are using them.
How could we solve that?

```
Events:
  Type     Reason         Age   From         Message
  ----     ------         ----  ----         -------
  Normal   Started        29s   PipelineRun  
  Warning  Failed         27s   PipelineRun  Pipeline /noop can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "openshift-client": the server could not find the requested resource (get clustertasks.tekton.dev openshift-client)
  Warning  InternalError  27s   PipelineRun  1 error occurred:
           * Couldn't retrieve Task "openshift-client": the server could not find the requested resource (get clustertasks.tekton.dev openshift-client)
```

**Comment by guillaumerose** [comment]
cc @jduimovich @sbose78

**Comment by Michkov** [comment]
Seems that default cluster tasks is feature of Red Hat OpenShift Pipelines, one component is ClusterTasks based on Tekton Catalog 0.28.

@guillaumerose here is bundle with noop pipeline without using ClusterTask:
```
  pipelineRef:
    name: noop
    bundle: quay.io/mkovarik/build-templates-bundle:noop-utils
```

**Comment by guillaumerose** [comment]
Thanks a lot. I have a working PR that bridges our 2 repos: https://github.com/openshift-pipelines/pipelines-service/pull/25

Will polish it and merge it.

**Comment by Michkov** [comment]
No cluster tasks used now.
