### ISSUE TITLE
Upload Snyk SAST results to snyk.io

### ISSUE THREAD

**Issue by lance** [redhat-appstudio/build-definitions#768]
For RHTAS prodsec compliance, we have been asked to provide links to systems or documents where it is shown how SAST findings are analyzed and processed by the team. With the current Konflux configuration, it is not straightforward to do this. Snyk Code results are stored as pipeline results, but are not shipped anywhere else during a pipelinerun. It would be ideal for us if the snyk results could be published to snyk.io using the [`--report` option for `snyk code test`](https://docs.snyk.io/snyk-cli/scan-and-maintain-projects-using-the-cli/snyk-cli-for-snyk-code/publish-snyk-code-cli-results-and-ignore-issues#commands-to-publish-snyk-code-cli-results). This feature appears to be in private beta, but it has been for about a year. Perhaps we could use it?

**Comment by mmorhun** [comment]
@lance we use Jira for issues. Please follow [STONEBLD-2129](https://issues.redhat.com/browse/STONEBLD-2129)
