### ISSUE TITLE
Consume the Pipeline definitions for App Studio Components

### ISSUE THREAD

**Issue by sbose78** [redhat-appstudio/build-definitions#9]
https://github.com/redhat-appstudio/infra-deployments/pull/53#issuecomment-1008068710

## Acceptance Criteria

The following tekton manifests should consume pipeline definitions from https://quay.io/repository/redhat-appstudio/build-templates-bundle?tab=tags which are built off https://github.com/redhat-appstudio/build-definitions/tree/main/pipelines/build-templates-bundle

* https://github.com/redhat-appstudio/infra-deployments/tree/main/components/gitops/.tekton
* https://github.com/redhat-appstudio/infra-deployments/tree/main/components/has/.tekton

**Comment by sbose78** [comment]
could be a good first issue for Michal Kovarik as well :)

**Comment by Michkov** [comment]
PR - https://github.com/redhat-appstudio/infra-deployments/pull/54

**Comment by Michkov** [comment]
redhat-appstudio/infra-deployments#54 merged, Pipelines are now consumed from bundle
